apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-images-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi